Bump morph
They recently switched from using the experimental nix(1) interface back
to the legacy nix-instantiate and friends. We can't currently deploy
because of issues caused by these experimental features, such as:

    error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override
    Error while running `nix eval ..`: exit status 1